### ISSUE TITLE
Чайник

### ISSUE THREAD

**Issue by BroadsideGC** [sandwwraith/os2016-conspect#4]
Купи норм чайник, а то не кипятит нихуя

**Comment by MrKich** [comment]
+

**Comment by OlegKuro** [comment]
При попытке вскипятить воду с помощью Леонида получил примерно ту же проблему. Пытался пробросить Лёню через плечо. Не помогло.
Bump!

**Comment by MrKich** [comment]
Сперва купи чайник, потом ишью закрывай

**Comment by sandwwraith** [comment]
Куплен новый чайник с подсветкой и управлением по Bluetooth. Время кипячения: 1,5 минуты.
